;(load "practica.lisp")

(defun area_triangulo()
    (princ "Escriba la base: ")
    (setq base (read))
    (princ "Escriba la altura: ")
    (setq altura (read))
    (write  (/ (* base altura) 2))
)

(defun area_rectangulo()
    (princ "Escriba la base: ")
    (setq base (read))
    (princ "Escriba la altura: ")
    (setq altura (read))
    (write  (* base altura))
)

(defun area_cuadrado()
    (princ "Escriba un lado: ")
    (setq lado (read))
    (write (* lado lado))
)

(defun area_circulo()
    (princ "Escriba el radio: ")
    (setq radio (read))
    (write (* radio radio 3.1416))
)

(defun area_rombo()
    (princ "Escriba D: ")
    (setq d1 (read))
    (princ "Escriba d: ")
    (setq d2 (read))
    (write (/ (* d1 d2) 2))
)

(defun area_trapecio()
    (princ "Escriba la altura: ")
    (setq altura (read))
    (princ "Escriba B: ")
    (setq b1 (read))
    (princ "Escriba b: ")
    (setq b2 (read))
    (write (/ (* (+ b1 b2) altura) 2))
)

(defun area_cometa()
    (princ "Escriba D: ")
    (setq d1 (read))
    (princ "Escriba d: ")
    (setq d2 (read))
    (write (* (/ d1 2) d2))    
)

(defun area_poligono_regular()
    (princ "Escriba el número de lados: ")
    (setq numero_lados (read))
    (princ "Escriba el valor de un lado: ")
    (setq lado (read))
    (setq angulo (/ 360 (* 2 numero_lados)))
    (setq apotema (/ lado (* 2 (tan (/ (* angulo 3.1416) 180)))))
    (write (/ (* apotema numero_lados lado) 2))
)

(defun area_corona_circular()
    (princ "Escriba R: ")
    (setq r (read))
    (princ "Escriba r: ")
    (setq r2 (read))
    (write (* 3.1416 (- (* r r) (* r2 r2))))
)

(defun area_sector_circular()
    (princ "Escriba el angulo: ")
    (setq angulo (read))
    (princ "Escriba el radio: ")
    (setq radio (read))
    (write (/ (* 3.1416 radio radio angulo) 360))
)

;Volumenes
(defun volumen_cubo()
    (princ "Escriba el valor de un lado: ")
    (setq lado (read))
    (format t "El volumen del cubo es: ~d unidades cubicas" (* lado lado lado))
)

(defun volumen_ortoedro()
    (princ "Escriba la longitud (a): ")
    (setq a (read))
    (princ "Escriba la latitud (b): ")
    (setq b (read))
    (princ "Escriba la altura (h): ")
    (setq h (read))
    (format t "El volumen del ortoedro es: ~d unidades cubicas" (* a b h))
)

(defun volumen_cilindro()
    (princ "Escriba el radio: ")
    (setq radio (read))
    (princ "Escriba la altura: ")
    (setq altura (read))
    (format t "El volumen del cilindro es: ~d unidades cubicas" (* 3.1416 radio radio altura))
)

(defun volumen_cono()
    (princ "Escriba la altura: ")
    (setq altura (read))
    (princ "Escriba el radio: ")
    (setq radio (read))
    (setq volumen (/ (* 3.1416 radio radio altura) 3))
    (format t "El volumen del cono es: ~d unidades cubicas" volumen)
)

(defun volumen_esfera()
    (princ "Escriba el radio: ")
    (setq radio (read))
    (format t "El volumen de la esfera es: ~d unidades cubicas" (/ (* 4 3.1416 (expt radio 3)) 3))
)

(defun volumen_tetraedro() 
    (princ "Escriba el valor de una arista: ")
    (setq arista (read))
    (format t "El volumen del tetraedro es: ~d unidades cubicas" (* (/ (sqrt 2) 12) (expt arista 3)))    
)

(defun volumen_piramide_triangular()
    (princ "Escriba el valor de la base: ")
    (setq base (read))
    (princ "Escriba el valor de la altura de la base: ")
    (setq altura_base (read))
    (princ "Escriba la altura de la piramide: ")
    (setq altura_piramide (read))
    (setq area (/ (* base altura_base) 2))
    (format t "El volumen de la piramide triangular es: ~d unidades cubicas." (/ (* area altura_piramide) 3))
)

(defun volumen_piramide_cuadrangular()
    (princ "Escriba el valor de la base: ")
    (setq base (read))
    (princ "Escriba el valor de la altura de la piramide: ")
    (setq altura (read))
    (format t "El volumen de la piramide cuadrangular es: ~d unidades cubicas" (/ (* (expt base 2) altura) 3))
)

(defun volumen_prisma_cuadrangular()
    (princ "Escriba el valor de la base: ")
    (setq base (read))
    (princ "Escriba la altura del prisma: ")
    (setq altura (read))
    (format t "El volumen del prisma cuadrangular es: ~d unidades cubicas" (* (expt base 2) altura))
)

(defun volumen_prisma_triangular()
    (princ "Escriba el valor de la base: ")
    (setq base (read))
    (princ "Escriba el valor de la altura de la base: ")
    (setq altura_base (read))
    (princ "Escriba el valor de la altura del prisma: ")
    (setq altura_prisma (read))
    (format t "El volumen del prisma triangular es: ~d unidades cubicas" (* (/ (* base altura_base) 2) altura_prisma))
)

